TIMING:
  TAP_MILLISEC: 250
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL

  - KEY: KEY_LEFTALT
    TAP: [KEY_LEFTMETA,KEY_W,]
    HOLD: KEY_LEFTALT

  - KEY: KEY_LEFTCTRL
    TAP: [KEY_LEFTMETA,KEY_T,]
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_RIGHTCTRL
    TAP: [KEY_LEFTALT,KEY_X,]
    HOLD: KEY_RIGHTCTRL

  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_LEFTSHIFT
    TAP: [ KEY_LEFTSHIFT, KEY_9, ]
    HOLD: KEY_LEFTSHIFT

  - KEY: KEY_RIGHTSHIFT
    TAP: KEY_LEFTMETA 
    HOLD: KEY_LEFTMETA 

  - KEY: KEY_LEFTMETA
    TAP: [ KEY_LEFTALT,KEY_F1, ]
    HOLD: KEY_LEFTMETA

  - KEY: KEY_RIGHTALT
    TAP: KEY_ESC  
    HOLD: KEY_HOME  

