# https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h
TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL

  - KEY: KEY_LEFTALT
    TAP: [KEY_LEFTMETA,KEY_W,]
    HOLD: KEY_LEFTALT   

  - KEY: KEY_LEFTCTRL
    TAP: [KEY_LEFTMETA,KEY_T,]
    HOLD: KEY_LEFTCTRL    

  - KEY: KEY_CAPSLOCK
    TAP: [KEY_LEFTMETA,KEY_E,]
    HOLD: KEY_LEFTCTRL      

  - KEY: KEY_LEFTSHIFT
    TAP: [ KEY_LEFTSHIFT, KEY_9, ]
    HOLD: KEY_LEFTSHIFT

  - KEY: KEY_RIGHTSHIFT
    TAP: [ KEY_RIGHTSHIFT, KEY_0, ]
    HOLD: KEY_RIGHTSHIFT

#   - KEY: KEY_KPENTER
#     TAP: KEY_KPENTER
#     HOLD: KEY_ESC


